# Generated by Django 5.1 on 2024-09-01 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "verbose_name": "Continent",
                "verbose_name_plural": "Continents",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "continent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countries",
                        to="coins.continent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="Coin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img_front",
                    models.ImageField(blank=True, upload_to="products_image"),
                ),
                ("img_back", models.ImageField(blank=True, upload_to="products_image")),
                (
                    "img_add_1",
                    models.ImageField(blank=True, upload_to="products_image"),
                ),
                (
                    "img_add_2",
                    models.ImageField(blank=True, upload_to="products_image"),
                ),
                ("denomination", models.CharField(max_length=150)),
                ("year", models.IntegerField()),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gold", "au"),
                            ("silver", "ag"),
                            ("platinum", "pt"),
                            ("palladium", "pd"),
                            ("copper", "cu"),
                            ("nickel", "ni"),
                            ("zinc", "zn"),
                            ("tin", "sn"),
                            ("bronze", "bronze"),
                            ("brass", "brass"),
                            ("cupronickel", "cupronickel"),
                            ("aluminum", "al"),
                            ("iron", "fe"),
                            ("lead", "pb"),
                            ("magnesium", "mg"),
                            ("magnetic metals", "magnetic metals"),
                            ("titanium", "ti"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "safety",
                    models.CharField(
                        blank=True,
                        choices=[("v", "v"), ("vf", "vf"), ("f", "f"), ("xf", "xf")],
                        max_length=2,
                    ),
                ),
                ("weight", models.FloatField(blank=True, null=True)),
                ("diameter", models.FloatField(blank=True, null=True)),
                ("thickness", models.FloatField(blank=True, null=True)),
                ("circulation", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("a", "active"),
                            ("e", "exchanged"),
                            ("w", "wait for delivery"),
                            ("s", "sent"),
                        ],
                        default="a",
                        max_length=1,
                    ),
                ),
                ("views_counter", models.IntegerField(default=0)),
                (
                    "box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coins",
                        to="coins.box",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coins",
                        to="coins.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coin",
                "verbose_name_plural": "Coins",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("topic", models.CharField(default="without topic", max_length=128)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="MultiOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("с", "under consideration"), ("d", "done")],
                        default="c",
                        max_length=1,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multi_offers_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coins_to_get",
                    models.ManyToManyField(related_name="offers_get", to="coins.coin"),
                ),
                (
                    "coins_to_give",
                    models.ManyToManyField(related_name="offers_give", to="coins.coin"),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multi_offers_look",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("с", "under consideration"), ("d", "done")],
                        default="c",
                        max_length=1,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coin_to_get",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_get",
                        to="coins.coin",
                    ),
                ),
                (
                    "coin_to_give",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_give",
                        to="coins.coin",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers_look",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_pic",
                    models.ImageField(blank=True, upload_to="coins/user_pic/"),
                ),
                ("phone", models.CharField(max_length=20)),
                ("postcode", models.CharField(max_length=10)),
                ("addres", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
