# Generated by Django 5.1 on 2025-01-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_userprofile_addres_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multioffer',
            name='message',
            field=models.TextField(blank=True, help_text='Message'),
        ),
    ]
