# Generated by Django 5.1 on 2025-01-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_multioffer_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('n', 'not active'), ('e', 'exchanged'), ('w', 'wait for delivery'), ('s', 'sent')], default='a', max_length=1),
        ),
    ]
